---
- name: Write timer file
  notify:
    - Restart custodian
  ansible.builtin.template:
    src: timer.j2
    dest: /etc/systemd/system/custodian.timer
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - custodian

- name: Write service file
  notify:
    - Restart custodian
  ansible.builtin.template:
    src: service.j2
    dest: /etc/systemd/system/custodian.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - custodian

- name: Pull docker image
  when: custodian_pull_image
  community.docker.docker_image:
    name: "{{ custodian_image }}"
    source: pull
  tags:
    - custodian

- name: Start custodian timer
  ansible.builtin.systemd:
    name: custodian.timer
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - custodian

...
