# Standards: 1.2
---
- name: Write timer file
  notify:
    - Restart custodian
  template:
    src: timer.j2
    dest: /etc/systemd/system/custodian.timer
  tags:
    - custodian

- name: Write service file
  notify:
    - Restart custodian
  template:
    src: service.j2
    dest: /etc/systemd/system/custodian.service
  tags:
    - custodian

- name: Start custodian timer
  systemd:
    name: custodian.timer
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - custodian

...
